[2023-11-26 16:28:06,981] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    print (query.cpf)
                      
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:28:07,074] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:28:07] "[35m[1mDELETE /cliente?cpf=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:28:57,668] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    print(query)
                 
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:28:57,694] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:28:57] "[35m[1mDELETE /cliente?cpf=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:36:48,589] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 16:36:48,615] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:36:48] "[35m[1mDELETE /cliente?cpf=1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:40:18,521] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000 - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:40:18,528] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:40:18,598] INFO _log() L224   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:07,051] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:07] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:07,688] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:07] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:08,188] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:08] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:08,525] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:08] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:09,138] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:09] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 16:41:09,223] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 16:41:09] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
