[2023-11-26 12:09:12,033] ERROR log_exception() L1449 Exception on /processo [POST] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 162, in add_processo
    processo = Processo(num_processo,
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__() takes 2 positional arguments but 3 were given
[2023-11-26 12:09:12,122] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:09:12] "[35m[1mPOST /processo HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 12:10:40,104] ERROR log_exception() L1449 Exception on /cliente [DELETE] - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 355, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\OneDrive\Área de Trabalho\MVP\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 119, in del_cliente
    cliente_cpf = unquote(unquote(query.cpf))
                          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\urllib\parse.py", line 671, in unquote
    if '%' not in string:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'float' is not iterable
[2023-11-26 12:10:40,117] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 12:10:40] "[35m[1mDELETE /cliente?cpf=10010010225 HTTP/1.1[0m" 500 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:30:25,122] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000 - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:30:25,126] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:31:18,010] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:31:18] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:32:25,142] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:32:25] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:32:36,753] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:32:36] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:33:27,445] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:33:27] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:33:37,168] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:33:37] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:33:48,234] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:33:48] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:44:09,686] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:44:09] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:44:36,260] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:44:36] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:44:40,707] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:44:40] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:47:49,160] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:47:49] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:47:52,381] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:47:52] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:51:16,257] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:51:16] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:51:19,065] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:51:19] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:59:11,663] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:59:11] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:59:14,672] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:59:14] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:59:56,280] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:59:56] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 14:59:58,734] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 14:59:58] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 15:10:19,449] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 15:10:19] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-11-26 15:10:22,732] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 15:10:22] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Hugo Nunes\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
